sudo: required
services:
  - docker

before_install:
  - docker build -t kovacevicdenis/fib-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kovacevicdenis/fib-client-test npm run test -- --coverage

after_success:
  - docker build -t kovacevicdenis/fib-client ./client
  - docker build -t kovacevicdenis/fib-nginx ./nginx
  - docker build -t kovacevicdenis/fib-server ./server
  - docker build -t kovacevicdenis/fib-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kovacevicdenis/fib-client
  - docker push kovacevicdenis/fib-nginx
  - docker push kovacevicdenis/fib-server
  - docker push kovacevicdenis/fib-worker